/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'nexus_core.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./nexus_core.android-arm64.node')
          } else {
            nativeBinding = require('nexus-core-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'nexus_core.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./nexus_core.android-arm-eabi.node')
          } else {
            nativeBinding = require('nexus-core-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'nexus_core.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./nexus_core.win32-x64-msvc.node')
          } else {
            nativeBinding = require('nexus-core-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'nexus_core.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./nexus_core.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('nexus-core-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'nexus_core.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./nexus_core.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('nexus-core-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'nexus_core.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./nexus_core.darwin-universal.node')
      } else {
        nativeBinding = require('nexus-core-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'nexus_core.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./nexus_core.darwin-x64.node')
          } else {
            nativeBinding = require('nexus-core-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'nexus_core.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./nexus_core.darwin-arm64.node')
          } else {
            nativeBinding = require('nexus-core-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'nexus_core.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./nexus_core.freebsd-x64.node')
      } else {
        nativeBinding = require('nexus-core-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { registerSyncTreeCallback, requestSplit, requestReplacePane, requestClosePane, requestToggleZoom, requestUpdateSizes, requestPatchLeaf, requestTearOff, requestTearIn, requestCloseTab, registerTab, initNexusCore, bootstrapWorkspace, applyWorkspaceNetwork, clearNetworkTopology, subscribePtyStream } = nativeBinding

module.exports.registerSyncTreeCallback = registerSyncTreeCallback
module.exports.requestSplit = requestSplit
module.exports.requestReplacePane = requestReplacePane
module.exports.requestClosePane = requestClosePane
module.exports.requestToggleZoom = requestToggleZoom
module.exports.requestUpdateSizes = requestUpdateSizes
module.exports.requestPatchLeaf = requestPatchLeaf
module.exports.requestTearOff = requestTearOff
module.exports.requestTearIn = requestTearIn
module.exports.requestCloseTab = requestCloseTab
module.exports.registerTab = registerTab
module.exports.initNexusCore = initNexusCore
module.exports.bootstrapWorkspace = bootstrapWorkspace
module.exports.applyWorkspaceNetwork = applyWorkspaceNetwork
module.exports.clearNetworkTopology = clearNetworkTopology
module.exports.subscribePtyStream = subscribePtyStream
