[package]
name = "getssh-vault"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "3.14.0"
napi-derive = "3.6.10"
aes-gcm = "0.11.1"
pbkdf2 = "0.13.0"
sha2 = "0.11.0"
rand = "0.10.3"
zeroize = { version = "1.8.1", features = ["zeroize_derive"] }

[build-dependencies]
napi-build = "2.3.2"
