/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Decrypts the vault payload.
 * Supports both V1 (legacy) and V2 (modern) formats.
 * V2 format: [Magic "GETSSH_V2" 9B] [Salt 32B] [IV 12B] [AuthTag 16B] [Ciphertext]
 * V1 format: [Salt 16B] [IV 12B] [AuthTag 16B] [Ciphertext]
 */
export declare function decryptVault(masterPassword: Buffer, encryptedPayload: Buffer): Buffer

/**
 * Encrypts the vault payload into V2 format.
 * Returns format: [Magic "GETSSH_V2" 9B] [Salt 32B] [IV 12B] [AuthTag 16B] [Ciphertext]
 */
export declare function encryptVault(masterPassword: Buffer, payload: Buffer): Buffer
