/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Extracts `zip_path` into `target_dir`.
 *
 * `target_dir` must be an existing, empty, real directory (not a symlink): nothing that was there
 * before can be overwritten, followed or deleted. On any error, everything this call created is
 * removed again and `target_dir` itself is left in place for the caller to dispose of.
 */
export declare function extractPlugin(zipPath: string, targetDir: string): Promise<void>
