/* auto-generated by NAPI-RS */
/* eslint-disable */

export interface CpuStats {
  overall: number
  cores: Array<number>
}

export declare function getSystemStats(): SystemStats

export interface MemStats {
  total: number
  free: number
  used: number
}

export interface NetStats {
  rx: number
  tx: number
}

export interface SystemStats {
  cpus: CpuStats
  mem: MemStats
  net: NetStats
}
