/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare class SftpDownloader {
  safePath: string
  dirPath?: string
  static create(maxSize: number, targetLocalPath?: string | undefined | null): SftpDownloader
  append(chunk: Buffer): void
  finish(): FinishResult
}

export declare class SftpUploader {
  static open(localPath: string): SftpUploader
  /** Reads up to `chunk_size` bytes (1 byte to 1 MiB); `None` means end of file. */
  readChunk(chunkSize: number): Buffer | null
  close(): void
}

export interface FinishResult {
  safePath: string
  dirPath?: string
}
