/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare function applyWorkspaceNetwork(workspaceId: string): Promise<string>

export declare function bootstrapWorkspace(workspaceId: string): Promise<string>

export declare function clearNetworkTopology(): Promise<string>

export declare function getTabSnapshot(tabId: string): Promise<string>

export declare function initTidalEngine(): Promise<string>

export declare function registerSyncTreeCallback(callback: (err: Error | null, payloadJson: string) => void): void

export declare function registerTab(tabId: string, rootPaneId: string, sessionId: string, paneType: string, configJson: string, title: string, workspaceId?: string | undefined | null): Promise<string>

export declare function requestClosePane(paneId: string): Promise<string>

export declare function requestCloseTab(tabId: string): Promise<string>

export declare function requestMarkSessionDisconnected(sessionId: string): Promise<string>

export declare function requestPatchLeaf(paneId: string, disconnected: boolean): Promise<string>

export declare function requestReplacePane(paneId: string, paneType: string, sessionId: string | undefined | null, configJson: string): Promise<string>

export declare function requestSplit(paneId: string, direction: string): Promise<string>

export declare function requestTearIn(tabId: string): Promise<string>

export declare function requestTearOff(paneId: string): Promise<string>

export declare function requestToggleZoom(paneId: string): Promise<string>

export declare function requestUpdateSizes(paneId: string, sizes: Array<number>): Promise<string>
