/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class AuditStream {
  constructor(outputPath: string, headerJson: string)
  writeFrame(timestamp: number, data: Buffer): void
  end(): void
}
