/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function initDb(dbPath: string): void
export declare function getVal(dbPath: string, key: string): string | null
export declare function setVal(dbPath: string, key: string, value: string): void
export declare function deleteVal(dbPath: string, key: string): void
export declare function clearVal(dbPath: string): void
export declare function getStorageSize(dbPath: string): number
