/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare function rehydrate(text: string, mappingDict: Record<string, string>): string

export declare function sanitize(text: string): SanitizeResult

export interface SanitizeResult {
  cleanText: string
  mappingDict: Record<string, string>
}
