/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface SanitizeResult {
  cleanText: string
  mappingDict: Record<string, string>
}
export declare function sanitize(text: string): SanitizeResult
export declare function rehydrate(text: string, mappingDict: Record<string, string>): string
